version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  app:
    build:
      context: .
    command: > 
      sh -c "./wait-for-it.sh -t 30 rabbitmq:5672 -- python main.py"
    env_file:
      - .env
    depends_on:
      - rabbitmq
#    restart: on-failure
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
